services:
  - type: web
    name: pravaah-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /docs
    envVars:
      - key: LIVEKIT_URL
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: NVIDIA_API_KEY
        sync: false
      - key: STT_PROVIDER
        value: groq_turbo
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
